# docker-compose.yml
version: "3"
services:
  mongodb:
    image: mongo
    container_name: kuna-mongo
    ports:
      - 27017:27017
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    volumes:
      - ./database/db:/data/db
  mongo-express:
    image: mongo-express
    container_name: client-mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped


